apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tekton-role
  namespace: default  # Change if needed
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/scale"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "taskruns"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tekton-sa
    namespace: default
roleRef:
  kind: Role
  name: tekton-role
  apiGroup: rbac.authorization.k8s.io