apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipelinerun-cicd-
spec:
  serviceAccountName: tekton-sa
  pipelineRef:
    name: pipeline-cicd
  params:
    - name: repo-url
      value: https://github.com/cafaray/diplo-cloud-notificacion-service.git
    - name: branch-name
      value: main
    - name: maven-image
      value: gcr.io/cloud-builders/mvn@sha256:8f38a2667125a8d83f6e1997847fedb6a06f041c90e2244884153d85d95f869b
    - name: image-name
      value: docker.io/cafaray/notificaciones:v2.6
    - name: deployment-name
      value: notificaciones-service
    # - name: deployment-manifest
    #   value: https://raw.githubusercontent.com/brightzheng100/tekton-pipeline-example/master/manifests/deployment.yaml
  workspaces:
    - name: maven-settings
      configmap:
        name: maven-settings
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
    - name: dockerconfig-ws
      secret:
        secretName: dockerconfig-ws
    - name: empty-dir
      emptyDir: {}
