apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: git-clone-
spec:
  taskRef:
    kind: Task
    name: git-clone
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
  - name: url
    value: https://github.com/cafaray/diplo-cloud-notificacion-service.git
  - name: deleteExisting
    value: "true"
  workspaces:
    - name: output
      # emptyDir when we don't need to share data accross tasks.
      # It holds a temporary directory that only lives as long as the TaskRun.
      # https://tekton.dev/docs/pipelines/workspaces/#emptydir
      # emptyDir: {}
      persistentVolumeClaim:
        claimName: workspace